name: Deploy Astro to Plesk (SFTP, Node 22)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "astro.config.*"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Envia apenas a pasta dist/ para o docroot do Plesk
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          password: ${{ secrets.PLESK_PASSWORD }}
          port: 22
          local_path: "./dist/*"
          remote_path: ${{ secrets.REMOTE_PATH }}
          delete: "true"
          sftp_only: "true"
